title: Jim Andrew Rogers | Singer Songwriter
email: info@jimandrewrogers.com

description: "Official website for Jim Andrew Rogers. Indie folk singer-songwriter who encapsulates introspective lyrics and melodies from the south coast, UK."
canvas: images/jar.JPG
baseurl: "https://www.jimandrewrogers.com" 
url: "https://www.jimandrewrogers.com"
twitter_username: jimandrewrogers
github_username:  JimRogers

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
exclude: [vendor]