title: Jim Andrew Rogers | Singer Songwriter | Official Website
email: info@jimandrewrogers.com

description: "Official website for indie folk singer-songwriter Jim Andrew Rogers. Rogers encapsulates introspective lyrics and melodies with folk-based sounds."
canvas: images/jar.JPG
baseurl: "https://jimandrewrogers.com" 
url: "https://jimandrewrogers.com"
twitter_username: jimandrewrogers
github_username:  JimRogers

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
exclude: [vendor]